# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Especifica la caja a usar
  config.vm.box = "bento/ubuntu-22.04"

  # Configuración de la red
  config.vm.network "private_network", ip: "192.168.33.10"

  # Configuración para el proveedor VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1500"
    vb.cpus = 2
  end
end

